title = "gitleaks config"
[[rules]]
    description = "RSA"
    regex = '''-----BEGIN RSA PRIVATE KEY-----'''
    [allowedlist]
    files = [
    ]
    paths = [
        '''src\/readme.md'''
    ]

# global allowed
[allowlist]
    files = [
        '''(.*?)(jpg|gif|doc|pdf|bin|svg|socket)$''',
        '''gitleaks-config\.toml$''',
#        '''readme.md'''
    ]
    paths = [
            '''src\/readme\.md$'''
    ]
